/* Generated by scripts/merge-trends.mjs from data/trends.json. Do not edit by hand. */
import type { Trend } from './data'

export const TRENDS_GENERATED_AT: string | null = null
export const TRENDS_SOURCES: string[] = []
export const TRENDS: Record<string, Trend> = {}
