/* Generated by scripts/merge-office.mjs from src/lib/data.ts. Do not edit by hand. */
export interface CatalogueProduct {
  id: string; name: string; brand: string; category: string; price: number
  variants: { id: string; label: string; delta: number }[]
  fulfil: { route: 'warehouse' | 'supplier'; origin: string }
  supplier?: { url: string; pid: string; vid: string; costUsd: number; termId: string }
  sellable: boolean
}
export const CATALOGUE_GENERATED_AT: string = "2026-10-03T14:20:06.656Z"
export const CATALOGUE: CatalogueProduct[] = [
  {
    "id": "xgimi-mogo-4-laser",
    "name": "MoGo 4 Laser",
    "brand": "XGIMI",
    "category": "Home cinema",
    "price": 1229,
    "variants": [
      {
        "id": "silver",
        "label": "Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "xgimi-vibe-one",
    "name": "Vibe One",
    "brand": "XGIMI",
    "category": "Home cinema",
    "price": 595,
    "variants": [
      {
        "id": "cloud-ash",
        "label": "Cloud Ash",
        "delta": 0
      },
      {
        "id": "blue-spark",
        "label": "Blue Spark",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "elite-yard-master-2-100",
    "name": "Yard Master 2, 100″",
    "brand": "Elite Screens",
    "category": "Home cinema",
    "price": 620,
    "variants": [
      {
        "id": "matte-white",
        "label": "Matte white",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "ringconn-gen-3",
    "name": "Gen 3 smart ring",
    "brand": "RingConn",
    "category": "Wearables",
    "price": 569,
    "variants": [
      {
        "id": "matte-black",
        "label": "Matte Black",
        "delta": 0
      },
      {
        "id": "future-silver",
        "label": "Future Silver",
        "delta": 0
      },
      {
        "id": "royal-gold",
        "label": "Royal Gold",
        "delta": 0
      },
      {
        "id": "brushed-silver",
        "label": "Brushed Silver",
        "delta": 30
      },
      {
        "id": "brushed-rose-gold",
        "label": "Brushed Rose Gold",
        "delta": 30
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "oura-ring-5",
    "name": "Ring 5",
    "brand": "Oura",
    "category": "Wearables",
    "price": 649,
    "variants": [
      {
        "id": "silver",
        "label": "Silver",
        "delta": 0
      },
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "gold",
        "label": "Gold",
        "delta": 150
      },
      {
        "id": "stealth",
        "label": "Stealth",
        "delta": 150
      },
      {
        "id": "brushed-silver",
        "label": "Brushed Silver",
        "delta": 150
      },
      {
        "id": "deep-rose",
        "label": "Deep Rose",
        "delta": 150
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "rayban-meta-gen-3",
    "name": "Meta Gen 3",
    "brand": "Ray-Ban",
    "category": "Wearables",
    "price": 679,
    "variants": [
      {
        "id": "shiny-black",
        "label": "Shiny Black",
        "delta": 0
      },
      {
        "id": "matte-black",
        "label": "Matte Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "bose-ultra-open-2",
    "name": "Ultra Open Earbuds (2nd Gen)",
    "brand": "Bose",
    "category": "Audio",
    "price": 449,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white-smoke",
        "label": "White Smoke",
        "delta": 0
      },
      {
        "id": "sky-pink",
        "label": "Sky Pink",
        "delta": 0
      },
      {
        "id": "cherry-chocolate",
        "label": "Cherry Chocolate",
        "delta": 0
      },
      {
        "id": "olive-green",
        "label": "Olive Green",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "plaud-notepin-s",
    "name": "NotePin S",
    "brand": "Plaud",
    "category": "Work",
    "price": 239,
    "variants": [
      {
        "id": "cosmic-gray",
        "label": "Cosmic Gray",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "anker-maggo-10k",
    "name": "MagGo Power Bank 10K (Qi2)",
    "brand": "Anker",
    "category": "Power",
    "price": 119.96,
    "variants": [
      {
        "id": "black-stone",
        "label": "Black Stone",
        "delta": 0
      },
      {
        "id": "shell-white",
        "label": "Shell White",
        "delta": 0
      },
      {
        "id": "ice-lake-blue",
        "label": "Ice Lake Blue",
        "delta": 0
      },
      {
        "id": "buds-green",
        "label": "Buds Green",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "anker-prime-100w",
    "name": "Prime Charger 100 W (GaN)",
    "brand": "Anker",
    "category": "Power",
    "price": 89.95,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "aqara-camera-e1",
    "name": "Camera E1",
    "brand": "Aqara",
    "category": "Smart home",
    "price": 89,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "nanoleaf-matter-strip-5m",
    "name": "Essentials Matter Lightstrip, 5 m",
    "brand": "Nanoleaf",
    "category": "Smart home",
    "price": 129,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "aqara-hub-m3",
    "name": "Hub M3",
    "brand": "Aqara",
    "category": "Smart home",
    "price": 297,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "eufy-x10-pro-omni",
    "name": "X10 Pro Omni",
    "brand": "eufy",
    "category": "Smart home",
    "price": 1299,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "segway-e3-pro",
    "name": "KickScooter E3 Pro",
    "brand": "Segway-Ninebot",
    "category": "Mobility",
    "price": 999,
    "variants": [
      {
        "id": "dark-grey",
        "label": "Dark Grey",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "bambu-a1-mini",
    "name": "A1 mini",
    "brand": "Bambu Lab",
    "category": "Maker",
    "price": 319,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "omnilux-contour-face",
    "name": "Contour Face",
    "brand": "Omnilux",
    "category": "Health",
    "price": 605,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "withings-body-smart",
    "name": "Body Smart",
    "brand": "Withings",
    "category": "Health",
    "price": 199,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "chipolo-pop",
    "name": "POP",
    "brand": "Chipolo",
    "category": "Accessories",
    "price": 50,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      },
      {
        "id": "blue",
        "label": "Blue",
        "delta": 0
      },
      {
        "id": "green",
        "label": "Green",
        "delta": 0
      },
      {
        "id": "red",
        "label": "Red",
        "delta": 0
      },
      {
        "id": "yellow",
        "label": "Yellow",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "esr-halolock-ring",
    "name": "HaloLock Universal Ring 360 (2-pack)",
    "brand": "ESR",
    "category": "Accessories",
    "price": 26.38,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      },
      {
        "id": "blue",
        "label": "Blue",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "sansai-au-travel-adapter",
    "name": "STV-017 inbound travel adapter",
    "brand": "Sansai",
    "category": "Accessories",
    "price": 12.05,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "warehouse",
      "origin": "AU"
    },
    "sellable": false
  },
  {
    "id": "samsung-the-freestyle-plus-2026",
    "name": "The Freestyle+ (2026)",
    "brand": "Samsung",
    "category": "Home cinema",
    "price": 1818,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "anker-nebula-capsule-3-laser",
    "name": "Capsule 3 Laser",
    "brand": "Anker Nebula",
    "category": "Home cinema",
    "price": 1136,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "dangbei-atom",
    "name": "Atom",
    "brand": "Dangbei",
    "category": "Home cinema",
    "price": 1362,
    "variants": [
      {
        "id": "dark-grey",
        "label": "Dark Grey",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "marshall-emberton-iii",
    "name": "Emberton III",
    "brand": "Marshall",
    "category": "Audio",
    "price": 197,
    "variants": [
      {
        "id": "black-and-brass",
        "label": "Black and Brass",
        "delta": 0
      },
      {
        "id": "cream",
        "label": "Cream",
        "delta": 0
      },
      {
        "id": "brown",
        "label": "Brown",
        "delta": 0
      },
      {
        "id": "sage",
        "label": "Sage",
        "delta": 0
      },
      {
        "id": "midnight-blue",
        "label": "Midnight Blue",
        "delta": 0
      },
      {
        "id": "black-and-silver",
        "label": "Black and Silver",
        "delta": 0
      },
      {
        "id": "vintage-black",
        "label": "Vintage Black",
        "delta": 0
      },
      {
        "id": "pitch-black",
        "label": "Pitch Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "UK"
    },
    "sellable": false
  },
  {
    "id": "sony-linkbuds-open",
    "name": "LinkBuds Open",
    "brand": "Sony",
    "category": "Audio",
    "price": 345,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "shokz-openfit-2-plus",
    "name": "OpenFit 2+",
    "brand": "Shokz",
    "category": "Audio",
    "price": 365,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "grey",
        "label": "Grey",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "nothing-ear-open",
    "name": "Ear (open)",
    "brand": "Nothing",
    "category": "Audio",
    "price": 150,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      },
      {
        "id": "blue",
        "label": "Blue",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "UK"
    },
    "sellable": false
  },
  {
    "id": "jbl-flip-7",
    "name": "Flip 7",
    "brand": "JBL",
    "category": "Audio",
    "price": 182,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "blue",
        "label": "Blue",
        "delta": 0
      },
      {
        "id": "red",
        "label": "Red",
        "delta": 0
      },
      {
        "id": "sand",
        "label": "Sand",
        "delta": 0
      },
      {
        "id": "funky-black",
        "label": "Funky Black",
        "delta": 0
      },
      {
        "id": "squad",
        "label": "Squad",
        "delta": 0
      },
      {
        "id": "pink",
        "label": "Pink",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      },
      {
        "id": "purple",
        "label": "Purple",
        "delta": 0
      },
      {
        "id": "turquoise",
        "label": "Turquoise",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "ugreen-nexode-100w-3-port",
    "name": "Nexode 100W 3-Port GaN Charger",
    "brand": "Ugreen",
    "category": "Power",
    "price": 73,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "anker-prime-26k-300w-power-bank",
    "name": "Prime Power Bank (26K, 300W)",
    "brand": "Anker",
    "category": "Power",
    "price": 303,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "belkin-boostcharge-pro-3-in-1-qi2-pad",
    "name": "BoostCharge Pro 3-in-1 Magnetic Charging Pad with Qi2 15W",
    "brand": "Belkin",
    "category": "Power",
    "price": 167,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "ultrahuman-ring-air",
    "name": "Ring AIR",
    "brand": "Ultrahuman",
    "category": "Wearables",
    "price": 529,
    "variants": [
      {
        "id": "raw-titanium",
        "label": "Raw Titanium",
        "delta": 0
      },
      {
        "id": "aster-black",
        "label": "Aster Black",
        "delta": 0
      },
      {
        "id": "matte-grey",
        "label": "Matte Grey",
        "delta": 0
      },
      {
        "id": "bionic-gold",
        "label": "Bionic Gold",
        "delta": 0
      },
      {
        "id": "space-silver",
        "label": "Space Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "samsung-galaxy-ring",
    "name": "Galaxy Ring",
    "brand": "Samsung",
    "category": "Wearables",
    "price": 606,
    "variants": [
      {
        "id": "titanium-black",
        "label": "Titanium Black",
        "delta": 0
      },
      {
        "id": "titanium-silver",
        "label": "Titanium Silver",
        "delta": 0
      },
      {
        "id": "titanium-gold",
        "label": "Titanium Gold",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "whoop-5-0",
    "name": "5.0",
    "brand": "WHOOP",
    "category": "Wearables",
    "price": 302,
    "variants": [
      {
        "id": "jet-black",
        "label": "Jet Black (CoreKnit band)",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "garmin-index-sleep-monitor",
    "name": "Index Sleep Monitor",
    "brand": "Garmin",
    "category": "Wearables",
    "price": 258,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "even-realities-g2",
    "name": "G2",
    "brand": "Even Realities",
    "category": "Wearables",
    "price": 908,
    "variants": [
      {
        "id": "grey1",
        "label": "Grey1",
        "delta": 0
      },
      {
        "id": "brown1",
        "label": "Brown1",
        "delta": 0
      },
      {
        "id": "green1",
        "label": "Green1",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "xreal-one",
    "name": "One",
    "brand": "XREAL",
    "category": "Wearables",
    "price": 605,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "meta-ray-ban-display",
    "name": "Ray-Ban Display",
    "brand": "Meta",
    "category": "Wearables",
    "price": 1211,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "sand",
        "label": "Sand",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "bee-pioneer",
    "name": "Pioneer",
    "brand": "Bee",
    "category": "Wearables",
    "price": 76,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "therabody-theraface-mask",
    "name": "TheraFace Mask",
    "brand": "Therabody",
    "category": "Health",
    "price": 985,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "currentbody-skin-led-mask-series-3",
    "name": "Skin LED Light Therapy Face Mask: Series 3",
    "brand": "CurrentBody",
    "category": "Health",
    "price": 864,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "UK"
    },
    "sellable": false
  },
  {
    "id": "withings-scanwatch-2",
    "name": "ScanWatch 2",
    "brand": "Withings",
    "category": "Wearables",
    "price": 561,
    "variants": [
      {
        "id": "black-silver",
        "label": "Black & Silver",
        "delta": 0
      },
      {
        "id": "white-silver",
        "label": "White & Silver",
        "delta": 0
      },
      {
        "id": "blue-rose-gold",
        "label": "Blue & Rose Gold",
        "delta": 0
      },
      {
        "id": "white-rose-gold",
        "label": "White & Rose Gold",
        "delta": 0
      },
      {
        "id": "blue-silver",
        "label": "Blue & Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "EU"
    },
    "sellable": false
  },
  {
    "id": "hyperice-normatec-elite",
    "name": "Normatec Elite Legs",
    "brand": "Hyperice",
    "category": "Health",
    "price": 1665,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "shark-cryoglow",
    "name": "CryoGlow",
    "brand": "Shark",
    "category": "Health",
    "price": 455,
    "variants": [
      {
        "id": "blue-frost",
        "label": "Blue Frost",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "switchbot-lock-ultra",
    "name": "Lock Ultra",
    "brand": "SwitchBot",
    "category": "Smart home",
    "price": 212,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "silver",
        "label": "Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "govee-rgbic-neon-rope-light-2",
    "name": "RGBIC Neon Rope Light 2",
    "brand": "Govee",
    "category": "Smart home",
    "price": 73,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      },
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "nanoleaf-blocks-starter-kit",
    "name": "Blocks Starter Kit",
    "brand": "Nanoleaf",
    "category": "Smart home",
    "price": 242,
    "variants": [
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "switchbot-hub-3",
    "name": "Hub 3",
    "brand": "SwitchBot",
    "category": "Smart home",
    "price": 182,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "aqara-smart-lock-u300",
    "name": "Smart Lock U300",
    "brand": "Aqara",
    "category": "Smart home",
    "price": 348,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "silver",
        "label": "Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "dreame-x50-ultra",
    "name": "X50 Ultra",
    "brand": "Dreame",
    "category": "Smart home",
    "price": 1515,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "roborock-saros-10",
    "name": "Saros 10",
    "brand": "Roborock",
    "category": "Smart home",
    "price": 1970,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "tp-link-tapo-c120",
    "name": "Tapo C120",
    "brand": "TP-Link",
    "category": "Smart home",
    "price": 61,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "philips-hue-play-hdmi-sync-box-8k",
    "name": "Play HDMI Sync Box 8K",
    "brand": "Philips Hue",
    "category": "Smart home",
    "price": 583,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "EU"
    },
    "sellable": false
  },
  {
    "id": "ecovacs-winbot-w2-pro-omni",
    "name": "Winbot W2 Pro Omni",
    "brand": "Ecovacs",
    "category": "Smart home",
    "price": 605,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "creality-k2",
    "name": "K2",
    "brand": "Creality",
    "category": "Maker",
    "price": 605,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "plaud-note-pro",
    "name": "Note Pro",
    "brand": "Plaud",
    "category": "Work",
    "price": 286,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "silver",
        "label": "Silver",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "flipper-zero",
    "name": "Zero",
    "brand": "Flipper",
    "category": "Maker",
    "price": 256,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "US"
    },
    "sellable": false
  },
  {
    "id": "raspberry-pi-5-desktop-kit-8gb",
    "name": "5 desktop kit (8 GB)",
    "brand": "Raspberry Pi",
    "category": "Maker",
    "price": 442,
    "variants": [
      {
        "id": "red-white",
        "label": "Red / white",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "UK"
    },
    "sellable": false
  },
  {
    "id": "dji-osmo-pocket-3",
    "name": "Osmo Pocket 3",
    "brand": "DJI",
    "category": "Work",
    "price": 665,
    "variants": [
      {
        "id": "standard",
        "label": "Standard",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "insta360-x5",
    "name": "X5",
    "brand": "Insta360",
    "category": "Work",
    "price": 833,
    "variants": [
      {
        "id": "midnight-black",
        "label": "Midnight Black",
        "delta": 0
      },
      {
        "id": "satin-white",
        "label": "Satin White (Limited Edition)",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "keychron-k2-he",
    "name": "K2 HE",
    "brand": "Keychron",
    "category": "Work",
    "price": 212,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      },
      {
        "id": "white",
        "label": "White",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "niu-kqi-300x",
    "name": "KQi 300X",
    "brand": "NIU",
    "category": "Mobility",
    "price": 1362,
    "variants": [
      {
        "id": "space-grey",
        "label": "Space Grey",
        "delta": 0
      },
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  },
  {
    "id": "segway-ninebot-kickscooter-f3",
    "name": "Ninebot KickScooter F3",
    "brand": "Segway",
    "category": "Mobility",
    "price": 1515,
    "variants": [
      {
        "id": "black",
        "label": "Black",
        "delta": 0
      }
    ],
    "fulfil": {
      "route": "supplier",
      "origin": "CN"
    },
    "sellable": false
  }
]
