/*
  Embed product photos as data URIs.

  Usage: node scripts/embed-photos.mjs
  Input:  photos/<product-id>-<n>.(jpg|jpeg|png|webp)   e.g. photos/xgimi-mogo-4-laser-1.jpg
  Output: src/lib/photos.generated.ts                     { [productId]: ['data:image/webp;base64,...', ...] }

  Each photo is centre-cropped to 4:3, resized to 1200 px wide and encoded as WebP at quality 82
  (roughly 60 to 90 KB each), so 21 products × 3 photos stays well under the published page's 16 MB limit.
  Photo 1 is the card and hero image; the rest go in the gallery.
*/
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import sharp from 'sharp'

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const inDir = path.join(root, 'photos')
const outFile = path.join(root, 'src', 'lib', 'photos.generated.ts')

if (!existsSync(inDir)) await mkdir(inDir, { recursive: true })

const files = (await readdir(inDir)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort()
const byProduct = new Map()

for (const f of files) {
  const m = f.match(/^(.+)-(\d+)\.(jpe?g|png|webp)$/i)
  if (!m) { console.warn(`skip ${f}: name must be <product-id>-<n>.<ext>`); continue }
  const [, id, n] = m
  const buf = await sharp(await readFile(path.join(inDir, f)))
    .rotate()
    .resize({ width: 1200, height: 900, fit: 'cover', position: 'attention', withoutEnlargement: false })
    .webp({ quality: 82, effort: 5 })
    .toBuffer()
  const list = byProduct.get(id) ?? []
  list.push({ n: Number(n), uri: `data:image/webp;base64,${buf.toString('base64')}`, bytes: buf.length })
  byProduct.set(id, list)
}

let total = 0
const entries = [...byProduct.entries()].map(([id, list]) => {
  list.sort((a, b) => a.n - b.n)
  for (const p of list) total += p.bytes
  console.log(`${id}: ${list.length} photo${list.length > 1 ? 's' : ''}, ${Math.round(list.reduce((s, p) => s + p.bytes, 0) / 1024)} KB`)
  return `  ${JSON.stringify(id)}: [\n${list.map((p) => `    ${JSON.stringify(p.uri)},`).join('\n')}\n  ],`
})

const out = `/* Generated by scripts/embed-photos.mjs. Do not edit: drop files into photos/<product-id>-1.jpg and run \`npm run photos\`. */
export const PHOTOS: Record<string, string[]> = {
${entries.join('\n')}
}
`
await writeFile(outFile, out)
console.log(`wrote ${path.relative(root, outFile)}: ${byProduct.size} products, ${Math.round(total / 1024)} KB of WebP`)
