/*
  data/trends.json → src/lib/trends.generated.ts. The shop imports the generated module at build,
  so the published page never fetches. An empty products map (the seed before the first run)
  yields TRENDS_GENERATED_AT = null and the shop keeps its sample trends, labelled as such.
  Usage: node scripts/merge-trends.mjs [root]
*/
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.argv[2] ? path.resolve(process.argv[2]) : path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const NAME = { wikipedia: 'Wikipedia', hackernews: 'Hacker News', reddit: 'Reddit', tiwib: 'TIWIB' }
let file = null
try { file = JSON.parse(await readFile(path.join(root, 'data', 'trends.json'), 'utf8')) } catch { file = null }
const products = file?.products ?? {}
const real = Object.keys(products).length > 0
const sources = real ? Object.entries(file.sources ?? {}).filter(([, v]) => v === 'ok').map(([k]) => NAME[k] ?? k) : []
const join = (xs) => (xs.length <= 1 ? xs.join('') : `${xs.slice(0, -1).join(', ')} and ${xs[xs.length - 1]}`)
const trends = {}
for (const [id, t] of Object.entries(products)) trends[id] = { label: t.label, delta: t.delta, series: t.series, source: join(sources) || 'Trend Radar signals' }
const header = `/* Generated by scripts/merge-trends.mjs from data/trends.json. Do not edit by hand. */
import type { Trend } from './data'

export const TRENDS_GENERATED_AT: string | null = ${real ? JSON.stringify(file.generatedAt) : 'null'}
export const TRENDS_SOURCES: string[] = ${JSON.stringify(sources)}
export const TRENDS: Record<string, Trend> = `
await mkdir(path.join(root, 'src', 'lib'), { recursive: true })
await writeFile(path.join(root, 'src', 'lib', 'trends.generated.ts'), header + JSON.stringify(trends, null, 2) + '\n')
console.log(`wrote src/lib/trends.generated.ts: ${Object.keys(trends).length} products${real ? ` from ${file.generatedAt}` : ' (no run yet)'}`)
