/*
  src/lib/data.ts (catalogue + expansion + Radar listings) → office/src/catalogue.generated.ts: what the
  Worker may sell and at what price. Only products with a supplier are sellable. Usage: node scripts/merge-office.mjs
*/
import { execFileSync } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..')
const script = `
import { products } from './src/lib/data'
const out = products.map((p) => ({ id: p.id, name: p.name, brand: p.brand, category: p.category, price: p.price,
  variants: p.variants.map((v) => ({ id: v.id, label: v.label, delta: v.delta ?? 0 })), fulfil: p.fulfil,
  ...(p.supplier ? { supplier: p.supplier } : {}), sellable: !!p.supplier }))
process.stdout.write(JSON.stringify(out))
`
const json = execFileSync('npx', ['tsx', '-e', script], { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
const items = JSON.parse(json)
const header = `/* Generated by scripts/merge-office.mjs from src/lib/data.ts. Do not edit by hand. */
export interface CatalogueProduct {
  id: string; name: string; brand: string; category: string; price: number
  variants: { id: string; label: string; delta: number }[]
  fulfil: { route: 'warehouse' | 'supplier'; origin: string }
  supplier?: { url: string; pid: string; vid: string; costUsd: number; termId: string }
  sellable: boolean
}
export const CATALOGUE_GENERATED_AT: string = ${JSON.stringify(new Date().toISOString())}
export const CATALOGUE: CatalogueProduct[] = `
await mkdir(path.join(root, 'office', 'src'), { recursive: true })
await writeFile(path.join(root, 'office', 'src', 'catalogue.generated.ts'), header + JSON.stringify(items, null, 2) + '\n')
console.log(`wrote office/src/catalogue.generated.ts: ${items.length} products, ${items.filter((i) => i.sellable).length} sellable`)
